-- 
-- Projet SIGOTI - CSCI_evae
-- 	Script de supression des tables
-- 	Safa & Hajar le 24/01/2014- 
--	

DROP TABLE "REPONSE_QUESTION" CASCADE CONSTRAINTS;
DROP TABLE "REPONSE_EVALUATION" CASCADE CONSTRAINTS;
DROP TABLE "QUESTION_EVALUATION" CASCADE CONSTRAINTS;
DROP TABLE "RUBRIQUE_EVALUATION" CASCADE CONSTRAINTS;
DROP TABLE "RUBRIQUE_QUESTION" CASCADE CONSTRAINTS;
DROP TABLE "RUBRIQUE" CASCADE CONSTRAINTS;
DROP TABLE "QUESTION" CASCADE CONSTRAINTS;
DROP TABLE "QUALIFICATIF" CASCADE CONSTRAINTS;
DROP TABLE "DROIT" CASCADE CONSTRAINTS;
DROP TABLE "EVALUATION" CASCADE CONSTRAINTS;