    
PROMPT Creating Check Constraint on 'RUBRIQUE'
ALTER TABLE RUBRIQUE
 ADD (CONSTRAINT AVCON_1393424886_TYPE_000 CHECK (TYPE IN ('RBP', 'RBS')))
/
     
PROMPT Creating Check Constraint on 'QUESTION'
ALTER TABLE QUESTION
 ADD (CONSTRAINT AVCON_1393424886_TYPE_001 CHECK (TYPE IN ('QUP', 'QUS')))
/
 
PROMPT Creating Check Constraint on 'REPONSE_QUESTION'
ALTER TABLE REPONSE_QUESTION
 ADD (CONSTRAINT AVCON_1393424886_POSIT_000 CHECK (POSITIONNEMENT BETWEEN 1 AND 5))
/
 