-- C:\temp\SMARTECH\EVAE\csci_evae.sqs
--
-- Generated for Oracle 10g on Wed Feb 26  15:28:06 2014 by Server Generator 10.1.2.11.12
 
PROMPT Creating Sequence 'QUA_SEQ'
CREATE SEQUENCE QUA_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'RUB_SEQ'
CREATE SEQUENCE RUB_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'QEV_SEQ'
CREATE SEQUENCE QEV_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'QUE_SEQ'
CREATE SEQUENCE QUE_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'REV_SEQ'
CREATE SEQUENCE REV_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'RPE_SEQ'
CREATE SEQUENCE RPE_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'EVE_SEQ'
CREATE SEQUENCE EVE_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'DRT_SEQ'
CREATE SEQUENCE DRT_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

