PROMPT Creating Unique Key on 'EVALUATION'
ALTER TABLE EVALUATION
 ADD (CONSTRAINT EVE_EVE_UK UNIQUE 
  (ANNEE_PRO
  ,NO_ENSEIGNANT
  ,NO_EVALUATION
  ,CODE_FORMATION
  ,CODE_UE))
/

PROMPT Creating Unique Key on 'DROIT'
ALTER TABLE DROIT
 ADD (CONSTRAINT DRT_DRT_UK UNIQUE 
  (NO_ENSEIGNANT
  ,ID_EVALUATION))
/
