
ALTER TABLE ETUDIANT
 ADD (CONSTRAINT ETU_PK PRIMARY KEY 
  (NO_ETUDIANT_NAT))
;
ALTER TABLE EMPLOYE
 ADD (CONSTRAINT EMP_PK PRIMARY KEY 
  (NO_CONTACT_ILI))
;
ALTER TABLE POSTE_ENTREPRISE
 ADD (CONSTRAINT POE_PK PRIMARY KEY 
  (NO_ETUDIANT_NAT
  ,NO_ENTREPRISE))
;
ALTER TABLE ENTREPRISE
 ADD (CONSTRAINT ENT_PK PRIMARY KEY 
  (NO_ENTREPRISE))
;
ALTER TABLE ENSEIGNANT
 ADD (CONSTRAINT ENS_PK PRIMARY KEY 
  (NO_ENSEIGNANT))
;
ALTER TABLE ELEMENT_CONSTITUTIF
 ADD (CONSTRAINT EC_PK PRIMARY KEY 
  (CODE_FORMATION
  ,CODE_UE
  ,CODE_EC))
;
ALTER TABLE PROMOTION
 ADD (CONSTRAINT PRO_PK PRIMARY KEY 
  (ANNEE_PRO
  ,CODE_FORMATION))
;
ALTER TABLE CANDIDAT
 ADD (CONSTRAINT CAN_PK PRIMARY KEY 
  (NO_ETUDIANT_NAT))
;
ALTER TABLE UNITE_ENSEIGNEMENT
 ADD (CONSTRAINT UE_PK PRIMARY KEY 
  (CODE_FORMATION
  ,CODE_UE))
;
ALTER TABLE DIPLOME
 ADD (CONSTRAINT DIP_PK PRIMARY KEY 
  (NO_ETUDIANT_NAT))
;
ALTER TABLE FORMATION
 ADD (CONSTRAINT FRM_PK PRIMARY KEY 
  (CODE_FORMATION))
;
