
CREATE INDEX ETU_PRO_FK_I ON ETUDIANT
 (ANNEE_PRO)
;

CREATE INDEX ETU_COM_FK_I ON ETUDIANT
 (CODE_COM)
;

CREATE INDEX EMP_ENT_FK_I ON EMPLOYE
 (NO_ENTREPRISE)
;

CREATE INDEX POE_DIP_FK_I ON POSTE_ENTREPRISE
 (NO_ETUDIANT_NAT)
;

CREATE INDEX POE_ENT_FK_I ON POSTE_ENTREPRISE
 (NO_ENTREPRISE)
;


CREATE INDEX EC_UE_FK_I ON ELEMENT_CONSTITUTIF
 (CODE_FORMATION
 ,CODE_UE)
;

CREATE INDEX EC_ENS_FK_I ON ELEMENT_CONSTITUTIF
 (NO_ENSEIGNANT)
;

CREATE INDEX PRO_FRM_FK_I ON PROMOTION
 (CODE_FORMATION)
;

CREATE INDEX PRO_STRE_FK_I ON PROMOTION
 (NO_EVALUATION)
;

CREATE INDEX PRO_NOTS_FK_I ON PROMOTION
 (NO_BAREME)
;

CREATE INDEX PRO_ENS_FK_I ON PROMOTION
 (NO_ENSEIGNANT)
;

CREATE INDEX CAN_PRO_FK_I ON CANDIDAT
 (ANNEE_PRO)
;

CREATE INDEX UE_ENS_FK_I ON UNITE_ENSEIGNEMENT
 (NO_ENSEIGNANT)
;

CREATE INDEX UE_FRM_FK_I ON UNITE_ENSEIGNEMENT
 (CODE_FORMATION)
;


