
ALTER TABLE ETUDIANT ADD (CONSTRAINT
 ETU_PRO_FK FOREIGN KEY 
  (CODE_FORMATION
  ,ANNEE_PRO) REFERENCES PROMOTION
  (CODE_FORMATION
  ,ANNEE_PRO))
;

ALTER TABLE EMPLOYE ADD (CONSTRAINT
 EMP_ENT_FK FOREIGN KEY 
  (NO_ENTREPRISE) REFERENCES ENTREPRISE
  (NO_ENTREPRISE))
;

ALTER TABLE EMPLOYE ADD (CONSTRAINT
 EMP_DIP_FK FOREIGN KEY 
  (NO_ETUDIANT_NAT) REFERENCES DIPLOME
  (NO_ETUDIANT_NAT))
;

ALTER TABLE POSTE_ENTREPRISE ADD (CONSTRAINT
 POE_DIP_FK FOREIGN KEY 
  (NO_ETUDIANT_NAT) REFERENCES DIPLOME
  (NO_ETUDIANT_NAT))
;

ALTER TABLE POSTE_ENTREPRISE ADD (CONSTRAINT
 POE_ENT_FK FOREIGN KEY 
  (NO_ENTREPRISE) REFERENCES ENTREPRISE
  (NO_ENTREPRISE))
;

ALTER TABLE ELEMENT_CONSTITUTIF ADD (CONSTRAINT
 EC_UE_FK FOREIGN KEY 
  (CODE_FORMATION
  ,CODE_UE) REFERENCES UNITE_ENSEIGNEMENT
  (CODE_FORMATION
  ,CODE_UE))
;

ALTER TABLE ELEMENT_CONSTITUTIF ADD (CONSTRAINT
 EC_ENS_FK FOREIGN KEY 
  (NO_ENSEIGNANT) REFERENCES ENSEIGNANT
  (NO_ENSEIGNANT))
;


ALTER TABLE PROMOTION ADD (CONSTRAINT
 PRO_ENS_FK FOREIGN KEY 
  (NO_ENSEIGNANT) REFERENCES ENSEIGNANT
  (NO_ENSEIGNANT))
;

ALTER TABLE PROMOTION ADD (CONSTRAINT
 PRO_FRM_FK FOREIGN KEY 
  (CODE_FORMATION) REFERENCES FORMATION
  (CODE_FORMATION))
;

ALTER TABLE CANDIDAT ADD (CONSTRAINT
 CAN_PRO_FK FOREIGN KEY 
  (CODE_FORMATION
  ,ANNEE_PRO) REFERENCES PROMOTION
  (CODE_FORMATION
  ,ANNEE_PRO))
;

ALTER TABLE UNITE_ENSEIGNEMENT ADD (CONSTRAINT
 UE_FRM_FK FOREIGN KEY 
  (CODE_FORMATION) REFERENCES FORMATION
  (CODE_FORMATION))
;

ALTER TABLE UNITE_ENSEIGNEMENT ADD (CONSTRAINT
 UE_ENS_FK FOREIGN KEY 
  (NO_ENSEIGNANT) REFERENCES ENSEIGNANT
  (NO_ENSEIGNANT))
;

ALTER TABLE DIPLOME ADD (CONSTRAINT
 DIP_ETU_FK FOREIGN KEY 
  (NO_ETUDIANT_NAT) REFERENCES ETUDIANT
  (NO_ETUDIANT_NAT))
;
