
ALTER TABLE QUESTION_EVALUATION
 ADD (CONSTRAINT QEV_PK PRIMARY KEY 
  (ID_QUESTION_EVALUATION))
;

ALTER TABLE EVALUATION
 ADD (CONSTRAINT EVE_PK PRIMARY KEY 
  (ID_EVALUATION))
;

ALTER TABLE RUBRIQUE
 ADD (CONSTRAINT RUB_PK PRIMARY KEY 
  (ID_RUBRIQUE))
;

ALTER TABLE RUBRIQUE_QUESTION
 ADD (CONSTRAINT RBQ_PK PRIMARY KEY 
  (ID_RUBRIQUE
  ,ID_QUESTION))
;

ALTER TABLE RUBRIQUE_EVALUATION
 ADD (CONSTRAINT REV_PK PRIMARY KEY 
  (ID_RUBRIQUE_EVALUATION))
;

ALTER TABLE QUALIFICATIF
 ADD (CONSTRAINT QUA_PK PRIMARY KEY 
  (ID_QUALIFICATIF))
;

ALTER TABLE DROIT
 ADD (CONSTRAINT DRT_PK PRIMARY KEY 
  (ID_EVALUATION
  ,NO_ENSEIGNANT))
;

ALTER TABLE QUESTION
 ADD (CONSTRAINT QUE_PK PRIMARY KEY 
  (ID_QUESTION))
;

ALTER TABLE REPONSE_QUESTION
 ADD (CONSTRAINT RPQ_PK PRIMARY KEY 
  (ID_REPONSE_QUESTION
  ,ID_QUESTION_EVALUATION))
;

ALTER TABLE REPONSE_EVALUATION
 ADD (CONSTRAINT RPE_PK PRIMARY KEY 
  (ID_REPONSE_EVALUATION))
;

