-- 
-- Jeu d'essai de la table ELEMENT_CONSTITUTIF
--
Insert into ELEMENT_CONSTITUTIF (CODE_FORMATION,CODE_UE,CODE_EC,NO_ENSEIGNANT,DESIGNATION,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
		values ('M2DOSI','SRE','SD',1,'WBS','Web Services',	10,10,10);

Insert into ELEMENT_CONSTITUTIF (CODE_FORMATION,CODE_UE,CODE_EC,NO_ENSEIGNANT,
				DESIGNATION,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
		values ('M2DOSI','SRE','SA',2,'DAM','Développement Application Mobile',10,10,10);

Insert into ELEMENT_CONSTITUTIF (CODE_FORMATION,CODE_UE,CODE_EC,NO_ENSEIGNANT,
				DESIGNATION,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
		values ('M2DOSI','WEB','AA',2,'AA','AAAAAAAAA',10,10,10);

Insert into ELEMENT_CONSTITUTIF (CODE_FORMATION,CODE_UE,CODE_EC,NO_ENSEIGNANT,
				DESIGNATION,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
		values ('M2DOSI','ISI','BB',2,'BB','BBBBBBBBBBBB',10,10,10);
