-- INSERTING into ENTREPRISE
Insert into "ENTREPRISE" ("NO_ENTREPRISE","REFERENCEE","DATE_REFERENCEMENT","LOGIN_CREA","DATE_CREA","NOM","SIEGE_SOCIAL","DOMAINE_ACTIVITE","ADRESSE","CP","VILLE","PAYS","TEL","SITE_INTERNET","NOM_REPRESENTANT","PRENOM_REPRESENTANT","LOGIN_MAJ","DATE_MAJ","OFFRE_STAGE") 
values (0,'N',null,null,to_date('2006-10-03','yyyy-mm-dd'),'Non définie','Non définie','SSII','Non définie','Non déf','Non définie','France','Non définie',null,null,null,null,to_date('2006-10-03','yyyy-mm-dd'),'N');
Insert into "ENTREPRISE" ("NO_ENTREPRISE","REFERENCEE","DATE_REFERENCEMENT","LOGIN_CREA","DATE_CREA","NOM","SIEGE_SOCIAL","DOMAINE_ACTIVITE","ADRESSE","CP","VILLE","PAYS","TEL","SITE_INTERNET","NOM_REPRESENTANT","PRENOM_REPRESENTANT","LOGIN_MAJ","DATE_MAJ","OFFRE_STAGE") 
values (1,'O',to_date('2006-10-03','yyyy-mm-dd'),'saliouph',to_date('2006-10-03','yyyy-mm-dd'),'THALES','Malakoff','SSII','34 Quai de la Douane','29200','BREST','France','02 98 43 44 66','www.thales-is.com',null,null,null,null,'O');
Insert into "ENTREPRISE" ("NO_ENTREPRISE","REFERENCEE","DATE_REFERENCEMENT","LOGIN_CREA","DATE_CREA","NOM","SIEGE_SOCIAL","DOMAINE_ACTIVITE","ADRESSE","CP","VILLE","PAYS","TEL","SITE_INTERNET","NOM_REPRESENTANT","PRENOM_REPRESENTANT","LOGIN_MAJ","DATE_MAJ","OFFRE_STAGE") 
values (2,'N',null,null,to_date('2006-10-03','yyyy-mm-dd'),'synapsy','CONCARNEAU','SSII','rue fulgence bienvenue','29900','CONCARNEAU','France','02 98 60 41 44','www.synapsy.fr','BARZIC','Ronan',null,null,'N');
Insert into "ENTREPRISE" ("NO_ENTREPRISE","REFERENCEE","DATE_REFERENCEMENT","LOGIN_CREA","DATE_CREA","NOM","SIEGE_SOCIAL","DOMAINE_ACTIVITE","ADRESSE","CP","VILLE","PAYS","TEL","SITE_INTERNET","NOM_REPRESENTANT","PRENOM_REPRESENTANT","LOGIN_MAJ","DATE_MAJ","OFFRE_STAGE") 
values (3,'O',to_date('2006-10-03','yyyy-mm-dd'),'saliouph',to_date('2006-10-03','yyyy-mm-dd'),'TEAMLOG','LANNION','SSII','11 r Blaise Pascal','22300','LANNION','France','02 96 48 21 22','Moulène','Bernard',null,null,null,'O');
Insert into "ENTREPRISE" ("NO_ENTREPRISE","REFERENCEE","DATE_REFERENCEMENT","LOGIN_CREA","DATE_CREA","NOM","SIEGE_SOCIAL","DOMAINE_ACTIVITE","ADRESSE","CP","VILLE","PAYS","TEL","SITE_INTERNET","NOM_REPRESENTANT","PRENOM_REPRESENTANT","LOGIN_MAJ","DATE_MAJ","OFFRE_STAGE") 
values (4,'O',to_date('2006-10-03','yyyy-mm-dd'),null,to_date('2006-10-03','yyyy-mm-dd'),'ASTEN','Brest','SSII','21 Rue Robert Schumann','29480','Le Relecq Kerhuon','France','02 98 28 66 60','www.groupe-asten.fr','CAGNARD','Jean-Christophe',null,null,'N');
Insert into "ENTREPRISE" ("NO_ENTREPRISE","REFERENCEE","DATE_REFERENCEMENT","LOGIN_CREA","DATE_CREA","NOM","SIEGE_SOCIAL","DOMAINE_ACTIVITE","ADRESSE","CP","VILLE","PAYS","TEL","SITE_INTERNET","NOM_REPRESENTANT","PRENOM_REPRESENTANT","LOGIN_MAJ","DATE_MAJ","OFFRE_STAGE") 
values (5,'N',null,null,to_date('2006-10-03','yyyy-mm-dd'),'Abase','Brest','SSII','zi Kerscao','29480','LE RELECQ KERHUON','France','02 98 30 43 60',null,null,null,null,null,'N');
Insert into "ENTREPRISE" ("NO_ENTREPRISE","REFERENCEE","DATE_REFERENCEMENT","LOGIN_CREA","DATE_CREA","NOM","SIEGE_SOCIAL","DOMAINE_ACTIVITE","ADRESSE","CP","VILLE","PAYS","TEL","SITE_INTERNET","NOM_REPRESENTANT","PRENOM_REPRESENTANT","LOGIN_MAJ","DATE_MAJ","OFFRE_STAGE") 
values (6,'N',null,null,to_date('2006-10-03','yyyy-mm-dd'),'Atlantide','Brest','SSII','300 r Pierre Rivoalon','29200','Brest','France',' 02 98 05 43 21',null,null,null,null,null,'N');
Insert into "ENTREPRISE" ("NO_ENTREPRISE","REFERENCEE","DATE_REFERENCEMENT","LOGIN_CREA","DATE_CREA","NOM","SIEGE_SOCIAL","DOMAINE_ACTIVITE","ADRESSE","CP","VILLE","PAYS","TEL","SITE_INTERNET","NOM_REPRESENTANT","PRENOM_REPRESENTANT","LOGIN_MAJ","DATE_MAJ","OFFRE_STAGE") 
values (7,'N',null,null,to_date('2006-10-03','yyyy-mm-dd'),'Capgemini','Brest','SSII','10 quai Commdt Malbert','29200','Brest','France','02 98 33 60 77',null,null,null,null,null,'N');
Insert into "ENTREPRISE" ("NO_ENTREPRISE","REFERENCEE","DATE_REFERENCEMENT","LOGIN_CREA","DATE_CREA","NOM","SIEGE_SOCIAL","DOMAINE_ACTIVITE","ADRESSE","CP","VILLE","PAYS","TEL","SITE_INTERNET","NOM_REPRESENTANT","PRENOM_REPRESENTANT","LOGIN_MAJ","DATE_MAJ","OFFRE_STAGE") 
values (8,'O',to_date('2006-10-03','yyyy-mm-dd'),null,to_date('2006-10-03','yyyy-mm-dd'),'Atos Origin','Brest','SSII','20 quai Commdt Malbert','29200','Brest','France','33 (0)2 98 80 97 30','www.si.fr.atosorigin.com',null,null,null,null,'O');
