-- INSERTING into ETUDIANT
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","CODE_FORMATION", "ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('6589RS236F','M1TIIL','2004-2005','CILI3.2','200056312','F','Arnaldi','Solenn',to_date('1980-03-19','yyyy-mm-dd'),'Guingamp','CEL','Française','06.88.55.78.97',null,'solenn.arnaldi@wanadoo.fr','17 rue Laënnec','29200','Brest','France','17 rue Laënnec','29200','Brest','France','Master1 Informatique','UBO Brest','SOA','arnaldso',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","CODE_FORMATION","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('164598','M1TIIL','2004-2005','CILI3.1','200056313','H','Beriard','François-Xavier',to_date('1981-07-18','yyyy-mm-dd'),'Charleville-mézières','CEL','Française','06.12.90.35.66','02.98.01.93.40','fx.beriard@apinc.org','142 rue Robespierre','29200','Brest','France','142 rue Robespierre','29200','Brest','France','Master1 Informatique','UBO Brest','FXB','beriarfr',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","CODE_FORMATION","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('0156523','M1TIIL','2004-2005','CILI3.1','200056314','H','Carriere','Guillaume',to_date('1982-06-17','yyyy-mm-dd'),'Brest','CEL','Française','06.76.94.89.85','02.98.92.77.34','gc@srbrest.com','16 rue Albert de Mun','29200','Brest','France','6 rue Albert de Mun','29200','Brest','France','Master1 Informatique','UBO Brest','GUC','carriegu',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","CODE_FORMATION","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('16894563','M1TIIL','2004-2005','CILI3.1','200056317','H','Frin','Ronan',to_date('1981-03-06','yyyy-mm-dd'),'Rennes','CEL','Française','06.63.92.05.30','02.99.64.04.78','frin_ronan@hotmail.com','1 rue A. Dodds','29200','Brest','France','16 rue Duguesclin','35590','L''hermitage','France','Master1 Informatique','UBO Brest','ROF','frinrona',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","CODE_FORMATION","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('20103526','M1TIIL','2004-2005','CILI3.1','200056318','F','Kerjean','Virginie',to_date('1981-03-28','yyyy-mm-dd'),'Brest','CEL','Française','06.62.35.78.79',null,'virginie_kerjean@yahoo.fr','199 rue du Commandant Drogou','29200','Brest','France','199 rue du Commandant Drogou','29200','Brest','France','Master1 Informatique','UBO Brest','VIK','kerjeavi',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","CODE_FORMATION","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('18986523','M1TIIL','2004-2005','CILI3.1','200056320','F','Le Vaillant','Sandrine',to_date('1981-08-03','yyyy-mm-dd'),'Brest','CEL','Française','06.85.01.54.07','02.98.05.09.64','sandrine_le_vaillant@yahoo.fr','1 rue Van-Gogh','29280','Plouzané','France','1 rue Van-Gogh','29280','Plouzané','France','Master1 Informatique','UBO Brest','SLV','levailla',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","CODE_FORMATION","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('20103546','M1TIIL','2004-2005','CILI3.2','200056321','F','Lemesle','Patricia',to_date('1981-06-03','yyyy-mm-dd'),'Morlaix','CEL','Française','06.13.66.36.01','02.98.72.00.61','pat.lemesle@wanadoo.fr','16 impasse de mouettes','29600','Morlaix','France','16 impasse de Mouettes','29600','Morlaix','France','Master1 Informatique','UBO Brest','PAL','lemespa',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","CODE_FORMATION","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('20168938','M1TIIL','2004-2005','CILI3.2','200056322','H','Lucas','Stéphane',to_date('1980-03-10','yyyy-mm-dd'),'Lannion','CEL','Française','06.23.39.47.52','02.96.37.74.92','stephane-joel.lucas@laposte.net','3 rue Lavoisier','22300','Lannion','France','3 rue Lavoisier','22300','Lannion','France','Master1 Informatique','UBO Brest','SLU','lucasste',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","CODE_FORMATION","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('142398A23C2','M1TIIL','2004-2005','CILI3.2','200056323','H','Mavic','Olivier',to_date('1980-03-07','yyyy-mm-dd'),'Quimper','CEL','Française','06.78.12.13.15','02.98.56.12.45','mavico@wanadoo.fr','17 rue de Kerjogu','29200','Brest','France','17 rue de Kerjogu','29200','Brest','France','Master1 Informatique','UBO Brest','OLM','mavicoli',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","CODE_FORMATION","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('361245','M1TIIL','2004-2005','CILI3.2','200056312','H','Troncal','Yannick',to_date('1979-06-04','yyyy-mm-dd'),'Angouleme','CEL','Française','06.82.20.99.71',null,'ytroncal@yahoo.fr','17 rue Kerabecam','29200','Brest','France','17 rue Kerabecam','29200','Brest','France','Master1 Informatique','UBO Brest','YAT','troncaya',null,null,null,null,'O');
