-- INSERTING into POSTE_ENTREPRISE
Insert into "POSTE_ENTREPRISE" ("NO_ETUDIANT_NAT","NO_ENTREPRISE","FONCTION","DATE_EMBAUCHE","MOYEN_OBTENTION","SERVICE","BRUT_ANNUEL") 
values ('6589RS236F',6,'IE',to_date('2005-09-01','yyyy-mm-dd'),'STA','EP',45000);
Insert into "POSTE_ENTREPRISE" ("NO_ETUDIANT_NAT","NO_ENTREPRISE","FONCTION","DATE_EMBAUCHE","MOYEN_OBTENTION","SERVICE","BRUT_ANNUEL") 
values ('18986523',8,'IE',to_date('2005-09-01','yyyy-mm-dd'),'STA','EP',35000);
Insert into "POSTE_ENTREPRISE" ("NO_ETUDIANT_NAT","NO_ENTREPRISE","FONCTION","DATE_EMBAUCHE","MOYEN_OBTENTION","SERVICE","BRUT_ANNUEL") 
values ('18986523',7,'IE',to_date('2006-01-01','yyyy-mm-dd'),'SPO','EP',40000);
Insert into "POSTE_ENTREPRISE" ("NO_ETUDIANT_NAT","NO_ENTREPRISE","FONCTION","DATE_EMBAUCHE","MOYEN_OBTENTION","SERVICE","BRUT_ANNUEL") 
values ('20168938',3,'IE',to_date('2005-09-01','yyyy-mm-dd'),'STA','EP',45000);
