-- 
-- Jeu d'essai de la table UNITE_ENSEIGNEMENT
--

Insert into UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,
				SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
		values 		('M2DOSI','WEB',2,'Langages du WEB',
				'9  ',null,null,null,48);
Insert into UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,
				SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP)
		values 		('M2DOSI','ISI',1,'Ingénierie des Systèmes d’Information',
				'9  ',null,20,20,20);
Insert into UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,
				SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
		values 		('M2DOSI','CO',1,'Conception Objet',
				'10 ',null,20,20,20);
        
Insert into UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,
				SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
		values 		('M2DOSI','IDL',1,'Ingénierie de Développement Logiciel',
				'10 ',null,20,20,20);
        
Insert into UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,
				SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
    values 		('M2DOSI','SRE',3,'Systèmes Répartis',
				'10 ',null,20,20,20);
