-- C:\temp\SMARTECH\ADM\view\csci_evae.vw
--
-- Generated for Oracle 10.2 on Wed Feb 26  12:16:16 2014 by Server Generator 10.1.2.11.12
 

PROMPT Creating View 'V_SERVICE'
CREATE OR REPLACE FORCE VIEW V_SERVICE
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'SERVICE'
/

PROMPT Creating View 'V_PROCESSUS_STAGE'
CREATE OR REPLACE FORCE VIEW V_PROCESSUS_STAGE
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'PROCESSUS_STAGE'
/

PROMPT Creating View 'V_DOMAINE_ACTIVITE'
CREATE OR REPLACE FORCE VIEW V_DOMAINE_ACTIVITE
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'DOMAINE_ACTIVITE'
/

PROMPT Creating View 'V_SEMESTRE'
CREATE OR REPLACE FORCE VIEW V_SEMESTRE
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'SEMESTRE'
/

PROMPT Creating View 'V_DIPLOME'
CREATE OR REPLACE FORCE VIEW V_DIPLOME
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'DIPLOME'
/

PROMPT Creating View 'V_TYPE_EMPLOI'
CREATE OR REPLACE FORCE VIEW V_TYPE_EMPLOI
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'TYPE_EMPLOI'
/

PROMPT Creating View 'V_FONCTION'
CREATE OR REPLACE FORCE VIEW V_FONCTION
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'FONCTION'
/

PROMPT Creating View 'V_MOYEN_OBTENTION_EMPLOI'
CREATE OR REPLACE FORCE VIEW V_MOYEN_OBTENTION_EMPLOI
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'MOYEN_OBTENTION_EMPLOI'
/

PROMPT Creating View 'V_OUI_NON'
CREATE OR REPLACE FORCE VIEW V_OUI_NON
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'OUI_NON'
/

