-- C:\temp\SMARTECH\ADM\csci_adm.ind
--
-- Generated for Oracle 10g on Wed Feb 26  11:57:54 2014 by Server Generator 10.1.2.11.12
  

PROMPT Creating Index 'ETU_PRO_FK_I'
CREATE INDEX ETU_PRO_FK_I ON ETUDIANT
 (ANNEE_PRO)
/

PROMPT Creating Index 'ETU_COM_FK_I'
CREATE INDEX ETU_COM_FK_I ON ETUDIANT
 (CODE_COM)
/

PROMPT Creating Index 'EMP_ENT_FK_I'
CREATE INDEX EMP_ENT_FK_I ON EMPLOYE
 (NO_ENTREPRISE)
/

PROMPT Creating Index 'POE_DIP_FK_I'
CREATE INDEX POE_DIP_FK_I ON POSTE_ENTREPRISE
 (NO_ETUDIANT_NAT)
/

PROMPT Creating Index 'POE_ENT_FK_I'
CREATE INDEX POE_ENT_FK_I ON POSTE_ENTREPRISE
 (NO_ENTREPRISE)
/


PROMPT Creating Index 'EC_UE_FK_I'
CREATE INDEX EC_UE_FK_I ON ELEMENT_CONSTITUTIF
 (CODE_FORMATION
 ,CODE_UE)
/

PROMPT Creating Index 'EC_ENS_FK_I'
CREATE INDEX EC_ENS_FK_I ON ELEMENT_CONSTITUTIF
 (NO_ENSEIGNANT)
/

PROMPT Creating Index 'PRO_FRM_FK_I'
CREATE INDEX PRO_FRM_FK_I ON PROMOTION
 (CODE_FORMATION)
/

PROMPT Creating Index 'PRO_STRE_FK_I'
CREATE INDEX PRO_STRE_FK_I ON PROMOTION
 (NO_EVALUATION)
/

PROMPT Creating Index 'PRO_NOTS_FK_I'
CREATE INDEX PRO_NOTS_FK_I ON PROMOTION
 (NO_BAREME)
/

PROMPT Creating Index 'PRO_ENS_FK_I'
CREATE INDEX PRO_ENS_FK_I ON PROMOTION
 (NO_ENSEIGNANT)
/

PROMPT Creating Index 'CAN_PRO_FK_I'
CREATE INDEX CAN_PRO_FK_I ON CANDIDAT
 (ANNEE_PRO)
/

PROMPT Creating Index 'UE_ENS_FK_I'
CREATE INDEX UE_ENS_FK_I ON UNITE_ENSEIGNEMENT
 (NO_ENSEIGNANT)
/

PROMPT Creating Index 'UE_FRM_FK_I'
CREATE INDEX UE_FRM_FK_I ON UNITE_ENSEIGNEMENT
 (CODE_FORMATION)
/


