-- C:\temp\SMARTECH\ADM\csci_adm.sqs
--
-- Generated for Oracle 10g on Wed Feb 26  11:57:54 2014 by Server Generator 10.1.2.11.12
 
PROMPT Creating Sequence 'EMP_SEQ'
CREATE SEQUENCE EMP_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'ENT_SEQ'
CREATE SEQUENCE ENT_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

