-- C:\temp\SMARTECH\ADM\csci_adm.tab
--
-- Generated for Oracle 10g on Wed Feb 26  11:57:54 2014 by Server Generator 10.1.2.11.12
 


PROMPT Creating Table 'ETUDIANT'
CREATE TABLE ETUDIANT
 (NO_ETUDIANT_NAT VARCHAR2(50) NOT NULL
 ,CODE_FORMATION VARCHAR2(8) NOT NULL
 ,ANNEE_PRO VARCHAR2(10) NOT NULL
 ,CODE_COM VARCHAR2(10)
 ,NO_ETUDIANT_UBO VARCHAR2(20)
 ,SEXE VARCHAR2(1) NOT NULL
 ,NOM VARCHAR2(50) NOT NULL
 ,PRENOM VARCHAR2(50) NOT NULL
 ,DATE_NAISSANCE DATE NOT NULL
 ,LIEU_NAISSANCE VARCHAR2(255) NOT NULL
 ,SITUATION VARCHAR2(3) NOT NULL
 ,NATIONALITE VARCHAR2(50) DEFAULT 'Française' NOT NULL
 ,TEL_PORT VARCHAR2(20)
 ,TEL_FIXE VARCHAR2(20)
 ,EMAIL VARCHAR2(255)
 ,ACTU_ADRESSE VARCHAR2(255)
 ,ACTU_CP VARCHAR2(10)
 ,ACTU_VILLE VARCHAR2(255)
 ,ACTU_PAYS VARCHAR2(255)
 ,PERM_ADRESSE VARCHAR2(255) NOT NULL
 ,PERM_CP VARCHAR2(10) NOT NULL
 ,PERM_VILLE VARCHAR2(255) NOT NULL
 ,PERM_PAYS VARCHAR2(255) NOT NULL
 ,DERNIER_DIPLOME VARCHAR2(255) NOT NULL
 ,UNIVERSITE VARCHAR2(255) NOT NULL
 ,SIGLE_ETU VARCHAR2(3) NOT NULL
 ,COMPTE_CRI VARCHAR2(10) NOT NULL
 ,UBO_EMAIL VARCHAR2(255)
 ,GRPE_ANGLAIS NUMBER(1)
 ,ABANDON_MOTIF VARCHAR2(255)
 ,ABANDON_DATE DATE
 ,EST_DIPLOME CHAR(1) DEFAULT 'N'
 )
/

COMMENT ON COLUMN ETUDIANT.NO_ETUDIANT_NAT IS 'Numéro National de l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.CODE_COM IS 'NE PAS UTILISER = RESIDU SIGILI'
/

COMMENT ON COLUMN ETUDIANT.NO_ETUDIANT_UBO IS 'Numéro UBO de l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.SEXE IS 'Représente le sexe des personnes'
/

COMMENT ON COLUMN ETUDIANT.NOM IS 'Nom de l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.PRENOM IS 'Prénom de l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.DATE_NAISSANCE IS 'Date de naiisance de l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.LIEU_NAISSANCE IS 'Lieu de naissance de l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.SITUATION IS 'Représente la situation de famille d''un étudiant'
/

COMMENT ON COLUMN ETUDIANT.NATIONALITE IS 'Nationalité de l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.TEL_PORT IS 'Numéro de portable de l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.TEL_FIXE IS 'Numéro de téléphone fixe de l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.EMAIL IS 'Adresse email de l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.ACTU_ADRESSE IS 'Rue de l''étudiant pendant l''anne scolaire'
/

COMMENT ON COLUMN ETUDIANT.ACTU_CP IS 'Code postal de l''étudiant pendant l''année scolaire'
/

COMMENT ON COLUMN ETUDIANT.ACTU_VILLE IS 'Ville de l''étudiant pendant l''année scolaire'
/

COMMENT ON COLUMN ETUDIANT.ACTU_PAYS IS 'Pays de l''étudiant pendant l''année scolaire'
/

COMMENT ON COLUMN ETUDIANT.PERM_ADRESSE IS 'Rue de l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.PERM_CP IS 'Code Postal de l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.PERM_VILLE IS 'Ville de l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.PERM_PAYS IS 'Pays de l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.DERNIER_DIPLOME IS 'Dernier diplôme obtenu par l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.UNIVERSITE IS 'Dernière université fréquenté par l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.SIGLE_ETU IS 'Sigle de l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.COMPTE_CRI IS 'Compte CRI de l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.UBO_EMAIL IS 'Adresse email UBO de l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.GRPE_ANGLAIS IS 'Groupe d''anglais de l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.ABANDON_MOTIF IS 'Motif de l''abandon de l''étudiant'
/

COMMENT ON COLUMN ETUDIANT.ABANDON_DATE IS 'Date à laquelle l''étudiant a abandonné la formation'
/

COMMENT ON COLUMN ETUDIANT.EST_DIPLOME IS 'Représenet une valeur booléen Oui ou Non'
/

PROMPT Creating Table 'EMPLOYE'
CREATE TABLE EMPLOYE
 (NO_CONTACT_ILI NUMBER NOT NULL
 ,NO_ENTREPRISE NUMBER NOT NULL
 ,NO_ETUDIANT_NAT VARCHAR2(50)
 ,NOM VARCHAR2(50) NOT NULL
 ,PRENOM VARCHAR2(50) NOT NULL
 ,MAIL_PRO VARCHAR2(100)
 ,TEL_PRO VARCHAR2(20)
 ,FONCTION VARCHAR2(5)
 )
/

COMMENT ON COLUMN EMPLOYE.FONCTION IS 'Représente le poste occupé au sein d''une entreprise'
/

PROMPT Creating Table 'POSTE_ENTREPRISE'
CREATE TABLE POSTE_ENTREPRISE
 (NO_ETUDIANT_NAT VARCHAR2(50) NOT NULL
 ,NO_ENTREPRISE NUMBER NOT NULL
 ,FONCTION VARCHAR2(5) NOT NULL
 ,DATE_EMBAUCHE DATE NOT NULL
 ,MOYEN_OBTENTION VARCHAR2(3) NOT NULL
 ,SERVICE VARCHAR2(5)
 ,BRUT_ANNUEL NUMBER(7)
 )
/

COMMENT ON COLUMN POSTE_ENTREPRISE.NO_ETUDIANT_NAT IS 'Numéro National de l''étudiant'
/

COMMENT ON COLUMN POSTE_ENTREPRISE.FONCTION IS 'Fonction du diplômé dans l''entreprise'
/

COMMENT ON COLUMN POSTE_ENTREPRISE.DATE_EMBAUCHE IS 'Date à laquelle le diplômé a été embauché dans l''entreprise'
/

COMMENT ON COLUMN POSTE_ENTREPRISE.MOYEN_OBTENTION IS 'Moyen d''obtention de l''emploi (suite à un stage, candidature spontannée...)'
/

COMMENT ON COLUMN POSTE_ENTREPRISE.SERVICE IS 'Service ou département dans l''entreprise'
/

COMMENT ON COLUMN POSTE_ENTREPRISE.BRUT_ANNUEL IS 'Salaire brut annuel du diplômé'
/

PROMPT Creating Table 'ENTREPRISE'
CREATE TABLE ENTREPRISE
 (NO_ENTREPRISE NUMBER NOT NULL
 ,REFERENCEE CHAR(1) DEFAULT 'N'
 ,DATE_REFERENCEMENT DATE
 ,LOGIN_CREA VARCHAR2(8)
 ,DATE_CREA DATE DEFAULT SYSDATE NOT NULL
 ,NOM VARCHAR2(100) NOT NULL
 ,SIEGE_SOCIAL VARCHAR2(100) NOT NULL
 ,DOMAINE_ACTIVITE VARCHAR2(5) NOT NULL
 ,ADRESSE VARCHAR2(255) NOT NULL
 ,CP VARCHAR2(10) NOT NULL
 ,VILLE VARCHAR2(100) NOT NULL
 ,PAYS VARCHAR2(100) DEFAULT 'FRANCE' NOT NULL
 ,TEL VARCHAR2(20) NOT NULL
 ,SITE_INTERNET VARCHAR2(150)
 ,NOM_REPRESENTANT VARCHAR2(50)
 ,PRENOM_REPRESENTANT VARCHAR2(50)
 ,LOGIN_MAJ VARCHAR2(8)
 ,DATE_MAJ DATE DEFAULT SYSDATE
 ,OFFRE_STAGE CHAR(1) DEFAULT 'N'
 )
/

COMMENT ON COLUMN ENTREPRISE.DATE_REFERENCEMENT IS 'Date de référencement de l''entreprise'
/

COMMENT ON COLUMN ENTREPRISE.LOGIN_CREA IS 'NE PAS UTILISER = RESIDU SIGILI'
/

COMMENT ON COLUMN ENTREPRISE.DATE_CREA IS 'Date de création de l''entreprise'
/

COMMENT ON COLUMN ENTREPRISE.NOM IS 'Nom de l''entreprise'
/

COMMENT ON COLUMN ENTREPRISE.SIEGE_SOCIAL IS 'Siège social de l''entreprise'
/

COMMENT ON COLUMN ENTREPRISE.DOMAINE_ACTIVITE IS 'Domaine d''activité de l''entreprise'
/

COMMENT ON COLUMN ENTREPRISE.ADRESSE IS 'Adresse de l''entreprise'
/

COMMENT ON COLUMN ENTREPRISE.CP IS 'Code postal de l''entreprise'
/

COMMENT ON COLUMN ENTREPRISE.VILLE IS 'Ville de l''entreprise'
/

COMMENT ON COLUMN ENTREPRISE.PAYS IS 'Pays de l''entreprise'
/

COMMENT ON COLUMN ENTREPRISE.TEL IS 'Téléphone de l''entreprise, peut contenir l''indicatif et des séparateurs'
/

COMMENT ON COLUMN ENTREPRISE.SITE_INTERNET IS 'Adresse web su site de l''entreprise'
/

COMMENT ON COLUMN ENTREPRISE.NOM_REPRESENTANT IS 'Nom du représentant'
/

COMMENT ON COLUMN ENTREPRISE.PRENOM_REPRESENTANT IS 'Prénom du représentant'
/

COMMENT ON COLUMN ENTREPRISE.LOGIN_MAJ IS 'NE PAS UTILISER = RESIDU SIGILI'
/

COMMENT ON COLUMN ENTREPRISE.DATE_MAJ IS 'Date de mise à jour des données'
/

COMMENT ON COLUMN ENTREPRISE.OFFRE_STAGE IS 'Représente une valeur booléen Oui ou Non'
/

PROMPT Creating Table 'ENTREPRISE_JN'
CREATE TABLE ENTREPRISE_JN
 (JN_OPERATION CHAR(3) NOT NULL
 ,JN_ORACLE_USER VARCHAR2(30) NOT NULL
 ,JN_DATETIME DATE NOT NULL
 ,JN_NOTES VARCHAR2(240)
 ,JN_APPLN VARCHAR2(35)
 ,JN_SESSION NUMBER(38)
 ,NO_ENTREPRISE NUMBER NOT NULL
 ,REFERENCEE CHAR(1)
 ,DATE_REFERENCEMENT DATE
 ,LOGIN_CREA VARCHAR2(8)
 ,DATE_CREA DATE
 ,NOM VARCHAR2(100)
 ,SIEGE_SOCIAL VARCHAR2(100)
 ,DOMAINE_ACTIVITE VARCHAR2(5)
 ,ADRESSE VARCHAR2(255)
 ,CP VARCHAR2(10)
 ,VILLE VARCHAR2(100)
 ,PAYS VARCHAR2(100)
 ,TEL VARCHAR2(20)
 ,SITE_INTERNET VARCHAR2(150)
 ,NOM_REPRESENTANT VARCHAR2(50)
 ,PRENOM_REPRESENTANT VARCHAR2(50)
 ,LOGIN_MAJ VARCHAR2(8)
 ,DATE_MAJ DATE
 ,OFFRE_STAGE CHAR(1)
 )
/

COMMENT ON TABLE ENTREPRISE_JN IS 'Created by Oracle Designer Server Generator'
/

PROMPT Creating Table 'ENSEIGNANT'
CREATE TABLE ENSEIGNANT
 (NO_ENSEIGNANT NUMBER(5) NOT NULL
 ,TYPE VARCHAR2(10) NOT NULL
 ,SEXE VARCHAR2(1) NOT NULL
 ,NOM VARCHAR2(50) NOT NULL
 ,PRENOM VARCHAR2(50) NOT NULL
 ,ADRESSE VARCHAR2(255) NOT NULL
 ,CP VARCHAR2(10) NOT NULL
 ,VILLE VARCHAR2(255) NOT NULL
 ,PAYS VARCHAR2(255) NOT NULL
 ,TEL_PORT VARCHAR2(20)
 ,ENC_PERSO_TEL VARCHAR2(20)
 ,ENC_UBO_TEL VARCHAR2(20)
 ,ENC_PERSO_EMAIL VARCHAR2(255)
 ,ENC_UBO_EMAIL VARCHAR2(255)
 ,INT_NO_INSEE VARCHAR2(50)
 ,INT_SOC_NOM VARCHAR2(50)
 ,INT_SOC_ADRESSE VARCHAR2(255)
 ,INT_SOC_CP VARCHAR2(10)
 ,INT_SOC_VILLE VARCHAR2(255)
 ,INT_SOC_PAYS VARCHAR2(255)
 ,INT_FONCTION VARCHAR2(50)
 ,INT_PROF_EMAIL VARCHAR2(255)
 ,INT_PROF_TEL VARCHAR2(20)
 )
/

COMMENT ON COLUMN ENSEIGNANT.NO_ENSEIGNANT IS 'Numéro unique de l''enseignant'
/

COMMENT ON COLUMN ENSEIGNANT.SEXE IS 'Représente le sexe des personnes'
/

COMMENT ON COLUMN ENSEIGNANT.NOM IS 'Nom de l''enseignant'
/

COMMENT ON COLUMN ENSEIGNANT.PRENOM IS 'Prénom de l''enseignant'
/

COMMENT ON COLUMN ENSEIGNANT.ADRESSE IS 'Rue de l''enseignant'
/

COMMENT ON COLUMN ENSEIGNANT.CP IS 'Code Postal de l''enseignant'
/

COMMENT ON COLUMN ENSEIGNANT.VILLE IS 'Ville de l''enseignant'
/

COMMENT ON COLUMN ENSEIGNANT.PAYS IS 'Pays de l''enseignant'
/

COMMENT ON COLUMN ENSEIGNANT.TEL_PORT IS 'Numéro de téléphone de l''enseignant'
/

COMMENT ON COLUMN ENSEIGNANT.ENC_PERSO_TEL IS 'Numéro de téléphone personnel de l''enseignant chercheur'
/

COMMENT ON COLUMN ENSEIGNANT.ENC_UBO_TEL IS 'Numéro de téléphone de l''UBO de l''enseignant chercheur'
/

COMMENT ON COLUMN ENSEIGNANT.ENC_PERSO_EMAIL IS 'Adresse email personnel de l''enseignant chercheur'
/

COMMENT ON COLUMN ENSEIGNANT.ENC_UBO_EMAIL IS 'Adresse email de l''UBO de l''enseignant chercheur'
/

COMMENT ON COLUMN ENSEIGNANT.INT_NO_INSEE IS 'Numéro INSEE de la société de l''intervenant extérieur'
/

COMMENT ON COLUMN ENSEIGNANT.INT_SOC_NOM IS 'Nom de la société de  l''intervenant extérieur'
/

COMMENT ON COLUMN ENSEIGNANT.INT_SOC_ADRESSE IS 'Rue de la société de  l''intervenant extérieur'
/

COMMENT ON COLUMN ENSEIGNANT.INT_SOC_CP IS 'Code postal de la société de  l''intervenant extérieur'
/

COMMENT ON COLUMN ENSEIGNANT.INT_SOC_VILLE IS 'Ville de la société de  l''intervenant extérieur'
/

COMMENT ON COLUMN ENSEIGNANT.INT_SOC_PAYS IS 'Pays de la société de  l''intervenant extérieur'
/

COMMENT ON COLUMN ENSEIGNANT.INT_FONCTION IS 'Fonction d el ''intervenant extérieur dans la société'
/

COMMENT ON COLUMN ENSEIGNANT.INT_PROF_EMAIL IS 'Adresse Email professionnel de l''intervenant extérieur'
/

COMMENT ON COLUMN ENSEIGNANT.INT_PROF_TEL IS 'Numéro de téléphone professionnel de l''intervenat extérieur'
/

PROMPT Creating Table 'ELEMENT_CONSTITUTIF'
CREATE TABLE ELEMENT_CONSTITUTIF
 (CODE_FORMATION VARCHAR2(8) NOT NULL
 ,CODE_UE VARCHAR2(8) NOT NULL
 ,CODE_EC VARCHAR2(8) NOT NULL
 ,NO_ENSEIGNANT NUMBER(5) NOT NULL
 ,DESIGNATION VARCHAR2(64) NOT NULL
 ,DESCRIPTION VARCHAR2(240) NOT NULL
 ,NBH_CM NUMBER(2)
 ,NBH_TD NUMBER(2)
 ,NBH_TP NUMBER(2)
 )
/

COMMENT ON TABLE ELEMENT_CONSTITUTIF IS 'Element Constitutif'
/

COMMENT ON COLUMN ELEMENT_CONSTITUTIF.CODE_FORMATION IS 'Code de la formation (Ex. : M2DOSI)'
/

COMMENT ON COLUMN ELEMENT_CONSTITUTIF.CODE_UE IS 'Code de l''Unité d''Enseignement (Ex. : PSI)'
/

COMMENT ON COLUMN ELEMENT_CONSTITUTIF.CODE_EC IS 'Code de l''Elément Constitutif (Ex. : SD pour Serveur de Données dans l''UE PSI'
/

COMMENT ON COLUMN ELEMENT_CONSTITUTIF.NO_ENSEIGNANT IS 'N° de l''enseignant responsable de l''EC'
/

COMMENT ON COLUMN ELEMENT_CONSTITUTIF.DESIGNATION IS 'Désignation de l''EC'
/

COMMENT ON COLUMN ELEMENT_CONSTITUTIF.NBH_CM IS 'Nb d''heures de CM prévues dans l''EC'
/

COMMENT ON COLUMN ELEMENT_CONSTITUTIF.NBH_TD IS 'Nb d''heures de TD prévues dans l''EC'
/

COMMENT ON COLUMN ELEMENT_CONSTITUTIF.NBH_TP IS 'Nb d''heures de TP prévues dans l''EC'
/

PROMPT Creating Table 'PROMOTION'
CREATE TABLE PROMOTION
 (CODE_FORMATION VARCHAR2(8) NOT NULL
 ,ANNEE_PRO VARCHAR2(10) NOT NULL
 ,NO_ENSEIGNANT NUMBER(5)
 ,SIGLE_PRO VARCHAR2(5) NOT NULL
 ,NB_ETU_SOUHAITE NUMBER(3) NOT NULL
 ,ETAT_PRESELECTION VARCHAR2(3) NOT NULL
 ,DATE_RENTREE DATE
 ,LIEU_RENTREE VARCHAR2(255)
 ,DATE_REPONSE_LP DATE
 ,COMMENTAIRE VARCHAR2(255)
 ,DATE_REPONSE_LALP DATE
 ,PROCESSUS_STAGE VARCHAR2(5) DEFAULT 'RECH'
 ,NO_EVALUATION NUMBER
 ,NO_BAREME NUMBER
 )
/

COMMENT ON COLUMN PROMOTION.ANNEE_PRO IS 'année scolaire de la promotion (2004-2005)'
/

COMMENT ON COLUMN PROMOTION.SIGLE_PRO IS 'Sigle de la promotion (ILI3)'
/

COMMENT ON COLUMN PROMOTION.NB_ETU_SOUHAITE IS 'Nombre d''étudiant que peut contenir au maximum la promotion'
/

COMMENT ON COLUMN PROMOTION.ETAT_PRESELECTION IS 'Représente l''état de la présélection des candidats d''une promotion'
/

COMMENT ON COLUMN PROMOTION.DATE_RENTREE IS 'Date à laquelle les étudiants font leur rentrée'
/

COMMENT ON COLUMN PROMOTION.LIEU_RENTREE IS 'Lieu où vont être accueilli les étudiants'
/

COMMENT ON COLUMN PROMOTION.DATE_REPONSE_LP IS 'Date (au plus tard) à laquelle les candidats sur liste principale doivent donnée leur réponse'
/

COMMENT ON COLUMN PROMOTION.COMMENTAIRE IS 'commentaire sur la promotion'
/

COMMENT ON COLUMN PROMOTION.DATE_REPONSE_LALP IS 'Date (au plus tard) à laquelle les candidats passés de la liste d''attente à la liste principale doivent donnée leur réponse'
/

COMMENT ON COLUMN PROMOTION.PROCESSUS_STAGE IS 'Représente la consultabilité de données'
/

PROMPT Creating Table 'CANDIDAT'
CREATE TABLE CANDIDAT
 (NO_ETUDIANT_NAT VARCHAR2(50) NOT NULL
 ,CODE_FORMATION VARCHAR2(8) NOT NULL
 ,ANNEE_PRO VARCHAR2(10) NOT NULL
 ,SEXE CHAR(1) NOT NULL
 ,NOM VARCHAR2(50) NOT NULL
 ,PRENOM VARCHAR2(50) NOT NULL
 ,DATE_NAISSANCE DATE NOT NULL
 ,LIEU_NAISSANCE VARCHAR2(255) NOT NULL
 ,SITUATION VARCHAR2(3) NOT NULL
 ,NATIONALITE VARCHAR2(50) DEFAULT 'Française' NOT NULL
 ,TEL_FIXE VARCHAR2(20)
 ,TEL_PORT VARCHAR2(20)
 ,EMAIL VARCHAR2(255)
 ,ACTU_ADRESSE VARCHAR2(255)
 ,ACTU_CP VARCHAR2(10)
 ,ACTU_VILLE VARCHAR2(255)
 ,ACTU_PAYS VARCHAR2(255)
 ,PERM_ADRESSE VARCHAR2(255) NOT NULL
 ,PERM_CP VARCHAR2(10) NOT NULL
 ,PERM_VILLE VARCHAR2(255) NOT NULL
 ,PERM_PAYS VARCHAR2(255) NOT NULL
 ,DERNIER_DIPLOME VARCHAR2(255) NOT NULL
 ,UNIVERSITE VARCHAR2(255) NOT NULL
 ,SELECTION_ORIGINE VARCHAR2(2) NOT NULL
 ,SELECTION_COURANTE VARCHAR2(2) NOT NULL
 ,REPONSE_ILI CHAR(1) DEFAULT 'N' NOT NULL
 ,DATE_REPONSE_ILI DATE
 ,REPONSE_CAN VARCHAR2(3) DEFAULT 'NRE'
 ,DATE_REPONSE_CAN DATE
 ,NO_ORDRE NUMBER
 )
/

COMMENT ON COLUMN CANDIDAT.NO_ETUDIANT_NAT IS 'numéro national de l''étudiant'
/

COMMENT ON COLUMN CANDIDAT.SEXE IS 'Représente le sexe des personnes'
/

COMMENT ON COLUMN CANDIDAT.NOM IS 'nom de famille du candidat'
/

COMMENT ON COLUMN CANDIDAT.PRENOM IS 'Prénom du candidat'
/

COMMENT ON COLUMN CANDIDAT.DATE_NAISSANCE IS 'date de naissance du candidat'
/

COMMENT ON COLUMN CANDIDAT.LIEU_NAISSANCE IS 'lieu de naissance du candidat'
/

COMMENT ON COLUMN CANDIDAT.SITUATION IS 'Représente la situation de famille d''un étudiant'
/

COMMENT ON COLUMN CANDIDAT.NATIONALITE IS 'Nationalité du candidat'
/

COMMENT ON COLUMN CANDIDAT.TEL_FIXE IS 'Numéro de téléphone fixe du candidat'
/

COMMENT ON COLUMN CANDIDAT.TEL_PORT IS 'Numéro de téléphone du portable du candidat'
/

COMMENT ON COLUMN CANDIDAT.EMAIL IS 'Adresse email du candidat'
/

COMMENT ON COLUMN CANDIDAT.ACTU_ADRESSE IS 'Rue du candidat pendant l''annee scolaire'
/

COMMENT ON COLUMN CANDIDAT.ACTU_CP IS 'Code Postel du candidat pendant l''annee scolaire'
/

COMMENT ON COLUMN CANDIDAT.ACTU_VILLE IS 'Ville du candidat pendant l''annee scolaire'
/

COMMENT ON COLUMN CANDIDAT.ACTU_PAYS IS 'Pays du candidat pendant l''annee scolaire'
/

COMMENT ON COLUMN CANDIDAT.PERM_ADRESSE IS 'Rue du candidat'
/

COMMENT ON COLUMN CANDIDAT.PERM_CP IS 'Code postal du candidat'
/

COMMENT ON COLUMN CANDIDAT.PERM_VILLE IS 'Ville du candidat'
/

COMMENT ON COLUMN CANDIDAT.PERM_PAYS IS 'Pays du candidat'
/

COMMENT ON COLUMN CANDIDAT.DERNIER_DIPLOME IS 'Dernier diplôme obtenu par le candidat'
/

COMMENT ON COLUMN CANDIDAT.UNIVERSITE IS 'Dernière université du candidat'
/

COMMENT ON COLUMN CANDIDAT.SELECTION_ORIGINE IS 'Représente la liste de selection d''un candidat'
/

COMMENT ON COLUMN CANDIDAT.SELECTION_COURANTE IS 'Représente la liste de selection d''un candidat'
/

COMMENT ON COLUMN CANDIDAT.REPONSE_ILI IS 'Représenet une valeur booléen Oui ou Non'
/

COMMENT ON COLUMN CANDIDAT.DATE_REPONSE_ILI IS 'Date à laquelle la réponse (accepté, attente, refus à la formation) a été envoyé au candidat'
/

COMMENT ON COLUMN CANDIDAT.REPONSE_CAN IS 'Représente la réponse d''un candidat au sujet de sa candidature'
/

COMMENT ON COLUMN CANDIDAT.DATE_REPONSE_CAN IS 'Date à laquelle le candidat a répondu (confirmé ou annulé sa participation à la formation)'
/

COMMENT ON COLUMN CANDIDAT.NO_ORDRE IS 'Classement du candidat sur la liste d''attente'
/

PROMPT Creating Table 'UNITE_ENSEIGNEMENT'
CREATE TABLE UNITE_ENSEIGNEMENT
 (CODE_FORMATION VARCHAR2(8) NOT NULL
 ,CODE_UE VARCHAR2(8) NOT NULL
 ,NO_ENSEIGNANT NUMBER(5) NOT NULL
 ,DESIGNATION VARCHAR2(64) NOT NULL
 ,SEMESTRE CHAR(3) NOT NULL
 ,DESCRIPTION VARCHAR2(256)
 ,NBH_CM INTEGER
 ,NBH_TD NUMBER(2)
 ,NBH_TP NUMBER(2)
 )
/

COMMENT ON TABLE UNITE_ENSEIGNEMENT IS 'Unité d''Enseignement'
/

COMMENT ON COLUMN UNITE_ENSEIGNEMENT.CODE_FORMATION IS 'Code de la formation (Ex. : M2DOSI)'
/

COMMENT ON COLUMN UNITE_ENSEIGNEMENT.CODE_UE IS 'Code de l''Unité d''Enseignement (Ex. : PSI)'
/

COMMENT ON COLUMN UNITE_ENSEIGNEMENT.NO_ENSEIGNANT IS 'N° de l''enseignant responsable de l''UC'
/

COMMENT ON COLUMN UNITE_ENSEIGNEMENT.DESIGNATION IS 'Désignation de l''UE'
/

COMMENT ON COLUMN UNITE_ENSEIGNEMENT.SEMESTRE IS 'N° de semestre dans lequel l''UE doit être dispensé'
/

COMMENT ON COLUMN UNITE_ENSEIGNEMENT.DESCRIPTION IS 'Description de l''UE'
/

COMMENT ON COLUMN UNITE_ENSEIGNEMENT.NBH_CM IS 'Nb d''heures de CM prévues dans l''UE'
/

COMMENT ON COLUMN UNITE_ENSEIGNEMENT.NBH_TD IS 'Nb d''heures de TD prévuesdans l''UE'
/

COMMENT ON COLUMN UNITE_ENSEIGNEMENT.NBH_TP IS 'Nb d''heures de TP prévues dans l''UE'
/

PROMPT Creating Table 'DIPLOME'
CREATE TABLE DIPLOME
 (NO_ETUDIANT_NAT VARCHAR2(50) NOT NULL
 ,NOM VARCHAR2(50) NOT NULL
 ,PRENOM VARCHAR2(50) NOT NULL
 ,AUTORISATION_ANNUAIRE CHAR(1) DEFAULT 'N' NOT NULL
 ,TYPE_EMPLOI VARCHAR2(3)
 ,MAIL_PRO VARCHAR2(100)
 ,TEL_PRO VARCHAR2(20)
 ,ADRESSE VARCHAR2(100)
 ,CP VARCHAR2(10)
 ,VILLE VARCHAR2(50)
 ,EMAIL_PERSO VARCHAR2(100)
 ,TEL_PERSO VARCHAR2(20)
 ,PORTABLE VARCHAR2(20)
 )
/

COMMENT ON COLUMN DIPLOME.NO_ETUDIANT_NAT IS 'Numéro National de l''étudiant'
/

COMMENT ON COLUMN DIPLOME.AUTORISATION_ANNUAIRE IS 'Représente une valeur booléen Oui ou Non'
/

COMMENT ON COLUMN DIPLOME.TYPE_EMPLOI IS 'Situation actuelle du diplômé'
/

COMMENT ON COLUMN DIPLOME.ADRESSE IS 'Adresse du diplômé'
/

COMMENT ON COLUMN DIPLOME.CP IS 'Code postal'
/

COMMENT ON COLUMN DIPLOME.VILLE IS 'Ville de résidence du diplômé'
/

COMMENT ON COLUMN DIPLOME.EMAIL_PERSO IS 'Second adresse mail du diplômé.'
/

PROMPT Creating Table 'FORMATION'
CREATE TABLE FORMATION
 (CODE_FORMATION VARCHAR2(8) NOT NULL
 ,DIPLOME VARCHAR2(3) NOT NULL
 ,N0_ANNEE NUMBER(1) DEFAULT 1 NOT NULL
 ,NOM_FORMATION VARCHAR2(64) NOT NULL
 ,DOUBLE_DIPLOME CHAR(1) NOT NULL
 ,DEBUT_HABILITATION DATE
 ,FIN_HABILITATION DATE
 )
/

COMMENT ON COLUMN FORMATION.CODE_FORMATION IS 'Code de la formation (Ex. : M2DOSI)'
/

COMMENT ON COLUMN FORMATION.DIPLOME IS 'Diplôme préparé : Licence, Master ou Doctorat.'
/

COMMENT ON COLUMN FORMATION.N0_ANNEE IS 'Année de formation (Ex.: 2 pour Licence 2)'
/

COMMENT ON COLUMN FORMATION.NOM_FORMATION IS 'Nom officielle de la formation'
/

COMMENT ON COLUMN FORMATION.DOUBLE_DIPLOME IS 'Indique s''il s''agit d''un double dipôme ou non'
/

COMMENT ON COLUMN FORMATION.DEBUT_HABILITATION IS 'Date de début de l''habilitation courante'
/

COMMENT ON COLUMN FORMATION.FIN_HABILITATION IS 'Date de fin de l''habilitation courante'
/

